In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px

In [ ]:
data=pd.read_csv('/content/StudentsPerformance.csv')

In [ ]:
data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
data.isna().any()

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course        False
math score                     False
reading score                  False
writing score                  False
dtype: bool

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
data.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
data.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
data.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
##### Parental education ####
df = data
fig = px.histogram(df,
                   x="parental level of education",
                   y=None, color="gender", width=600, height=400,
                   barmode= 'group',
                   histnorm='percent',
                   category_orders={
                       "parental level of education": ["some high school", "high school", "associate's degree", "some college", "bachelor's degree", "master's degree"],
                       "gender": ["male", "female"]
                },

                color_discrete_map={
                    "male": "lightblue", "female": "lightsalmon"
                },
                template="simple_white"
                )

fig.update_layout(title="<b> Parental Level of Education",
                  font_family="San Serif",
                  titlefont={'size': 24},
                  legend=dict(
                  orientation="v", y=1, yanchor="top", x=1.0, xanchor="right" )
                 )
fig.show()

In [ ]:
##### race #####

fig = px.histogram(df, x="race/ethnicity", y=None, color="gender",
                width=600, height=400, barmode='group',
                histnorm='percent',
                category_orders={
                "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"],
                "gender": ["male", "female"]
                },
                color_discrete_map={
                    "male": "lightblue", "female": "lightsalmon"
                },
                template="simple_white"
                )

fig.update_layout(title="<b> Race/Ethnic Group",
                  font_family="San Serif",
                  titlefont={'size': 24},
                  legend=dict(
                  orientation="v", y=1, yanchor="top", x=1.0, xanchor="right" )
                 )

fig.show()

In [ ]:
fig = px.histogram(df, x="lunch", y=None, color="gender",
                width=600, height=400, barmode='group',
                histnorm='percent',
                color_discrete_map={
                    "male": "lightblue", "female": "lightsalmon"
                },
                template="simple_white"
                )

fig.update_layout(title="<b> Lunch Type",
                  font_family="San Serif",
                  titlefont={'size': 24},
                  legend=dict(
                  orientation="v", y=1, yanchor="top", x=1.0, xanchor="right" )
                 )
fig.show()

In [ ]:
#### test prep ####
fig = px.histogram(df, x="test preparation course", y=None, color="gender",
                width=600, height=400, barmode='group',
                histnorm='percent',
                color_discrete_map={
                    "male": "lightblue", "female": "lightsalmon"
                },
                template="simple_white"
                )

fig.update_layout(title="<b> Test Preparation Course",
                  font_family="San Serif",
                  titlefont={'size': 24},
                  legend=dict(
                  orientation="v", y=1, yanchor="top", x=1.0, xanchor="right" )
                 )
fig.show()

In [ ]:
# maths
fig = px.box(df,
                 x="test preparation course", y="math score",
                 facet_col="gender",
                 color='gender',
                 template='simple_white',
                 width=750, height=350,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Test preparation course on math score",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

In [ ]:
fig=px.box(df,x="test preparation course",y="reading score",
           facet_col="gender",
           color='gender',
           template='simple_white',
           width=750,height=350,category_orders={
               "race/ethnicity":["group A","group B","group C","group D","group E"]
           })
fig.update_layout(
    title="Test preparation course on reading score",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

In [ ]:
fig = px.box(df,
                 x="test preparation course", y="writing score",
                 facet_col="gender",
                 color='gender',
                 template='simple_white',
                 width=750, height=350,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Test preparation course on writing score",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

In [ ]:

fig = px.box(df,
                 x="test preparation course", y="writing score",
                 facet_col="race/ethnicity",
                 color='gender',
                 template='simple_white',
                 width=1500, height=350,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Test preparation course on writing score: variation accros race group",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

In [ ]:
DF = df[(df['race/ethnicity'] == 'group B') | (df['race/ethnicity'] == 'group C')]

fig = px.box(DF,
                 x="test preparation course", y="writing score",
                 facet_col="parental level of education",
                 color='gender',
                 template='simple_white',
                 width=2000, height=350,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Test preparation course on writing score: variation across ParentEduc (group B&C)",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

In [ ]:
fig = px.box(df,
                 x="lunch", y="math score",
                 facet_col="gender",
                 color='gender',
                 template='simple_white',
                 width=900, height=400,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Lunch on math score",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

# reading
fig = px.box(df,
                 x="lunch", y="reading score",
                 facet_col="gender",
                 color='gender',
                 template='simple_white',
                 width=900, height=400,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Lunch on reading score",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

# writing
fig = px.box(df,
                 x="lunch", y="writing score",
                 facet_col="gender",
                 color='gender',
                 template='simple_white',
                 width=900, height=400,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Lunch on writing score",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()

# writing, race
fig = px.box(df,
                 x="lunch", y="math score",
                 facet_col="race/ethnicity",
                 color='gender',
                 template='simple_white',
                 width=900, height=400,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Lunch on math score: variation across race group",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()


# # writing, race, parent education
DF = df[(df['race/ethnicity'] == 'group A') & (df['gender'] == 'female')]

fig = px.box(DF,
                 x="lunch", y="writing score",
                 color="parental level of education",
#                  facet_col=
#                  color='gender',
                 template='simple_white',
                 width=900, height=400,
                 category_orders={
                     "race/ethnicity": ["group A", "group B", "group C", "group D", "group E"]
                     }
                )

fig.update_layout(
    title="Lunch on writing score: variation across ParentEduc. (female students of group A) ",
    margin=dict(l=20, r=20, t=70, b=20, pad=1),
    paper_bgcolor="lightgray",
)
fig.show()